In [1]:
import pandas as pd

from sklearn.metrics import accuracy_score
import joblib
import argparse
from xgboost import XGBRegressor

def cargar_datos(archivo_csv):
    """Cargar datos desde un archivo CSV."""
    return pd.read_csv(archivo_csv)

def entrenar_modelo(X_train, y_train):
    """Entrenar un modelo de regresión logística."""
    modelo = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
    modelo.fit(X_train, y_train)
    return modelo

def guardar_modelo(modelo, nombre_archivo):
    """Guardar el modelo entrenado en un archivo."""
    joblib.dump(modelo, nombre_archivo)

def main():
    # Argumentos de línea de comandos
    parser = argparse.ArgumentParser(description="Entrenar un modelo con un archivo CSV.")
    parser.add_argument("archivo_csv", type=str, help="Ruta al archivo CSV con los datos. La última columna deber ser la variable objetivo.")
    parser.add_argument("modelo_salida", type=str, help="Ruta donde se guardará el modelo entrenado.")
    args = parser.parse_args()

    # Cargar datos
    datos = cargar_datos(args.archivo_csv)
    
    # Separar las características (X) y la etiqueta (y)
    # Suponiendo que la última columna es la etiqueta
    X_train = datos.iloc[:, :-1]  # Todas las columnas excepto la última
    y_train = datos.iloc[:, -1]   # Última columna


    # Entrenar el modelo
    modelo = entrenar_modelo(X_train, y_train)

    # Guardar el modelo entrenado
    guardar_modelo(modelo, args.modelo_salida)
    print(f"Modelo guardado en: {args.modelo_salida}")

if __name__ == "__main__":
    main()

usage: ipykernel_launcher.py [-h] archivo_csv modelo_salida
ipykernel_launcher.py: error: the following arguments are required: modelo_salida

SystemExit: 2

C:\Users\rhuer\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [3]:
import pandas as pd

from sklearn.metrics import accuracy_score
import joblib
import argparse
from xgboost import XGBRegressor

In [9]:
archivo_csv = 'C:/Users/rhuer/OneDrive/Escritorio/MaestríaITAM/02_Primavera_2025/ProductosDeDatos/T03/data/datos_OHE.csv'
x = pd.read_csv(archivo_csv)

In [11]:
x

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial,SalePrice
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,1,0,208500
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,1,0,181500
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,1,0,223500
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,0,0,0,0,0,140000
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,1,0,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,0,0,1,0,0,0,1,0,175000
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,1,0,0,0,1,0,210000
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,0,0,1,0,0,0,1,0,266500
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,0,0,1,0,0,0,1,0,142125
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,0,0,0,1,0,0,0,1,0,147500